### ISSUE TITLE
Question about LV MYO RV values in your paper?

### ISSUE THREAD

**Issue by AliMedVisionTech** [SLDGroup/CASCADE#12]
Thanks for your outstanding work. Can you share the version of the test.py code that outputs the values of LV MYO RV? Besides, I have successfully run your code but obtained the values of 12 test cases on the ACDC dataset but still struggling to understand how you obtained the LV MYO RV values.

![Capture](https://github.com/SLDGroup/CASCADE/assets/37287234/27b0696d-08ee-41e3-881f-14e1a164c739)

**Comment by mostafij-rahman** [comment]
Hi,

We appreciate your feedback. We log the LV MYO RV values in a text file at "test_log//.txt".
