### ISSUE TITLE
The parameters and the FLOPs for PVT-CASCADE and TransCASCADE

### ISSUE THREAD

**Issue by 1580827935** [SLDGroup/CASCADE#13]
![图片](https://github.com/SLDGroup/CASCADE/assets/117509706/a7241fa5-a3ec-49ba-ac40-7df2cc8754a8)
Can you tell me the parameters and the  FLOPs for PVT-CASCADE and TransCASCADE on the Synapse dataset?I want to make a comparison in my paper.Thank you!!!

**Comment by mostafij-rahman** [comment]
Hi,

Our PVT-CASCADE has 34.13M params and 5.84G FLOPS. You can try to get stats of TransCASCADE using 'get_model_complexity_info' function from the python 'ptflops' or some other similar libraries.

Best,
Mostafij

**Comment by 1580827935** [comment]
Thanks for your help！

-From a rookie postgraduate
