### ISSUE TITLE
About the ACDC dataset processing

### ISSUE THREAD

**Issue by distancezsx** [SLDGroup/CASCADE#2]
Great work! Could you explain how the ACDC dataset is preprocessed or related preprocessing code？Thank you!

**Comment by mostafij-rahman** [comment]
We appreciate your feedback.

We use the preprocessed data from [MT-UNet](https://github.com/Dootmaan/MT-UNet). You can download the preprocessed data from [Google Drive of MT-UNet](https://drive.google.com/file/d/13qYHNIWTIBzwyFgScORL2RFd002vrPF2/view).

Thank you!

Mostafij
