### ISSUE TITLE
Why use the same SA module for 4 Convolution Attention Module?

### ISSUE THREAD

**Issue by ghost** [SLDGroup/CASCADE#4]
In your paper, you use 4 Convolution attention modules (CAM) at 4 different stages, where each CAM has a Channel attention (CA), Spatial attention (SA), and finally, a Conv block.

![Screenshot 2023-04-13 015225](https://user-images.githubusercontent.com/101169545/231556827-e6a1454f-d463-4a45-974a-d90a2a9c2480.png)

If following the above architecture you provide, I will understand that 4 CAMs will have 4 different CAs, 4 SAs, and 4 Conv blocks.

![Screenshot 2023-04-13 015305](https://user-images.githubusercontent.com/101169545/231557184-2d2f31c7-590e-428e-a876-621628fac093.png)

But after I read your code, I see that there is only one SA declared and shared for 4 CAMs. Can you tell me why you do this? Sorry if I have missed something in your paper that I have this issue.
Thank you

**Comment by mostafij-rahman** [comment]
Yes, in our implementation, we use a shared _SpatialAttention_ block in all our 4 _CAM_ modules. We call `self.SA` in each _CAM_ module of the forward function.

Thanks.
Mostafij

**Comment by ghost** [comment]
Thanks for your reply
But i still don't understand why you only declared a single SA and shared for 4 CAMs. Is it better than declaring 4 different SAs for 4 CAMs?

**Comment by mostafij-rahman** [comment]
It's really a good question. By declaring a single shared SA, we can reduce the number of params without significantly losing Dice score.  

Thanks,
Mostafij
