### ISSUE TITLE
Details of training

### ISSUE THREAD

**Issue by aixiaobaikkk** [SLDGroup/CASCADE#6]
Dear author, can you share your hyperparameter settings?

**Comment by mostafij-rahman** [comment]
Hi aixiaobaikk,

You will find the hyperparameter settings used in our experiments in the source code of this repo as well as in our paper. 

We appreciate your interest in CASCADE.

Best,
Mostafij

**Comment by aixiaobaikkk** [comment]
thanks a lot,it's a great job,I will go on studying it



---- Replied Message ----
| From | Md Mostafijur ***@***.***> |
| Date | 06/09/2023 23:06 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [SLDGroup/CASCADE] Details of training (Issue #6) |

Hi aixiaobaikk,

You will find the hyperparameter settings used in our experiments in the source code of this repo as well as in our paper.

We appreciate your interest in CASCADE.

Best,
Mostafij
