### ISSUE TITLE
wrong label dict?

### ISSUE THREAD

**Issue by garlicman-man** [SLDGroup/CASCADE#9]
In the test_synapse.py
You provided this one
classes = ['spleen', 'right kidney', 'left kidney', 'gallbladder', 'pancreas', 'liver', 'stomach', 'aorta']

But after double checking, when I use the Transunet's preprocessed data, the label is wrong, and I think it should be:
classes = ['spleen', 'right kidney', 'left kidney', 'gallbladder', 'liver', 'pancreas', 'stomach', 'aorta']

Thanks

**Comment by mostafij-rahman** [comment]
Hi, 
We did not use TransUnet preprocessed data; rather we wrote a preprocessing file (utils/preprocess_synapse_data.py) following their instructions. In our preprocessing, the label dict matches with the original labels.  

Thank you. Hope it helps.

Best,
Mostafij
